### ISSUE TITLE
Data scope

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-herbarium-germany#1]
Hi @jholetschek

I can help adding the data scope if needed, but I need some help figuring out what it should be.

The project descriptions mentions that it is scoped by datasets, but not which. 

> 767,120 specimens from 15 institutions (20 datasets)

**Comment by jholetschek** [comment]
Hi Morten,

I've attached a list oft dataset UUIDs... will that work?
There might be additional datasets in the future - is there a way to update the filter later on?

Cheers from Berlin,
Jörg
[datasets.txt](https://github.com/gbif/hp-herbarium-germany/files/5893689/datasets.txt)

**Comment by timrobertson100** [comment]
@ahahn-gbif - would this warrant being a network entity perhaps?

We can identify an administrator, it is a clearly bounded group and has a web portal (hosted).

**Comment by MortenHofft** [comment]
Yes, we can always update the filter later on. Either as a list of datasets or a a network. If we decide to go for a network, then you can use the registry interface to do so.

**Comment by ahahn-gbif** [comment]
@timrobertson100  - I agree that would make good sense, though we do not yet have all the pieces in place to make that a fully independent administrative entity for curation. I am missing part one of the conversation - @jholetschek, can you catch me up on the overall scope of the grouping, please?

**Comment by jholetschek** [comment]
Hi Andrea, Tim,
the portal is intended for digitised specimens of German herbaria, it's called Virtual Herbarium /de. There is already an aged portal that is supposed to be replaced by the HP. There is currently an initiative for getting funding for a complete digitisation of German herbaria, so it's not only intended for scientific use by botanists, but also as a show case for the collections.

**Comment by timrobertson100** [comment]
Is the dataset composition relatively static (a few additions a year) @jholetschek or something changing very regularly please?

**Comment by jholetschek** [comment]
It's rather static... there might be a new dataset every few months or so. Growth will mainly come from rising record numbers of the individual datasets.

**Comment by MortenHofft** [comment]
The site has been updated to use the network as a data scope. @jholetschek you have access to edit the network datasets
https://registry.gbif.org/network/3aee7756-565e-4dc5-b22c-f997fbd7105c

the change is visible on the  staging site

Be aware that the data needs reprocessing first so currently it appears empty

**Comment by MortenHofft** [comment]
The data need to be reprocessed for this to show I assume @muttcg ?
